services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DEBUG=${DEBUG:-True}
    env_file: ${HOME}/secrets/ccm/.env
    ports:
      - 4000:4000
      - 4020:4020
    volumes:
      - ./ccm_web/client/src:/code/ccm_web/client/src
      - ./backend:/code/backend
      - ${HOME}/secrets/ccm:/secrets
    container_name: ccm_web
    depends_on:
      - database

  database:
    image: mysql:8-oracle
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--socket=/tmp/mysql.sock']
    environment:
      - MYSQL_ROOT_PASSWORD=ccm_root_pw
      - MYSQL_HOST=ccm_db
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=ccm
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 5400:3306
    volumes:
      - ./.mysql_data:/var/lib/mysql
    container_name: ccm_db
