version: '3.9'

services:

  web:
    build:
      context: ./ccm_web/
      dockerfile: ./Dockerfile
      args:
        - PORT=4000
    environment:
      - PORT=4000
      - NODE_ENV=production
    env_file: .env
    entrypoint: sh -c './node_modules/.bin/wait-port ccm_db_prod:3306 && ./start.sh'
    ports:
      - 4000:4000
    container_name: ccm_web_prod
    depends_on:
      - database

  database:
    image: mysql:8-oracle
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--socket=/tmp/mysql.sock']
    environment:
      - MYSQL_ROOT_PASSWORD=ccm_root_pw
      - MYSQL_HOST=ccm_db_prod
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=ccm
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 5400:3306
    volumes:
      - ./.mysql_data_prod:/var/lib/mysql
    container_name: ccm_db_prod
