name: CCM Build/Release

on:
  push:
    # takes muliple branch names
    branches: 
<<<<<<< HEAD
      - main
=======
      - master
>>>>>>> a7ff2ea (Adding a github actions file)
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].*' # 2021.01.x
      - i404_BE_dep_update
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]' # 2021.01.01
 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'YYYY.MINOR.MICRO'
env:
  REPO_URL: ${{ github.repository }}
    
jobs:
  build:
    # to test a feature, change the repo name to your github id
    if: github.repository_owner == 'tl-its-umich-edu' || github.repository_owner == 'pushyamig'
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout code 
<<<<<<< HEAD
<<<<<<< HEAD
        uses: actions/checkout@v4
=======
        uses: actions/checkout@v3
>>>>>>> a7ff2ea (Adding a github actions file)
=======
        uses: actions/checkout@v4
>>>>>>> 9878d68 (updating the github action repos version)
    
      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=$(basename ${{ github.ref }})" >> $GITHUB_ENV
      
      - name: build Docker image
        run: |
          cd ccm_web
          docker build . --tag ghcr.io/${{ env.REPO_URL }}:${BRANCH_NAME}
      
      - name: Login to GitHub Container Registry
<<<<<<< HEAD
<<<<<<< HEAD
        uses: docker/login-action@v3
=======
        uses: docker/login-action@v2
>>>>>>> a7ff2ea (Adding a github actions file)
=======
        uses: docker/login-action@v3
>>>>>>> 9878d68 (updating the github action repos version)
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.REPO_URL }}:${BRANCH_NAME}
    
  release: 
     # Making sure that release only runs for tag pushes
    if: startsWith(github.ref, 'refs/tags/') && github.repository_owner == 'pushyamig'
    needs: build # This ensures the build job finishes successfully before starting this job
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@v4
=======
      - uses: actions/checkout@v3
>>>>>>> a7ff2ea (Adding a github actions file)
=======
      - uses: actions/checkout@v4
>>>>>>> 5bf1369 (Git action version update)

      - name: Draft Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      